# Generated by Django 3.0 on 2022-03-30 13:20

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='время удаления')),
                ('datetime_live', models.DateTimeField(blank=True, default=models.DateTimeField(blank=True, null=True, verbose_name='время удаления'), null=True, verbose_name='время удаления')),
                ('describe', models.CharField(max_length=255, verbose_name='описание')),
                ('todo', models.CharField(max_length=255, verbose_name='задание')),
                ('is_active', models.BooleanField(default=True, verbose_name='активность')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': (builtins.id,),
            },
        ),
    ]
